### ISSUE TITLE
Type library breaks parsing

### ISSUE THREAD

**Issue by DefaultUser1606** [StefH/RamlToOpenApiConverter#21]
If I reference a library in a raml file, the parser breaks with an error below
`Invalid cast from 'System.String' to 'System.Collections.Generic.IDictionary``

Raml example:
```
#%RAML 1.0
baseUri: https://www.redacted.com/
title: test
version: v1
mediaType: application/json
securedBy: [openIdConnect, null]
uses:
  libtype: typelibrary.raml
			
types:
  MyLibraryType: libtype.MyLibraryType
```

Library example:
```
#%RAML 1.0 Library
usage: usage desc
types:
# Base types MUST BE defined first
  MyLibraryType:
    type: object
    properties: 
      channelId: 
        type: string
        required: true
        pattern: "^[a-zA-Z0-9]{8}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{4}-[a-zA-Z0-9]{12}$"
      name: 
        type: string
        required: true
        maxLength: 100
```

This happens both in ConvertToOpenApiDocument and in ConvertToFile methods.
